/**
 * The contents of this file are subject to the license and copyright
 * detailed in the LICENSE and NOTICE files at the root of the source
 * tree and available online at
 *
 * https://github.com/chinamds/license/
 */
// Created using LayerGen 4.0

package com.mds.aiotplayer.msg.model;

import com.mds.aiotplayer.common.model.DataEntity;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.mds.aiotplayer.common.model.JsonDateSerializer;

import org.hibernate.annotations.Type;
import org.hibernate.search.annotations.DocumentId;
import org.hibernate.search.annotations.Field;
import org.hibernate.search.annotations.FieldBridge;
import org.hibernate.search.annotations.Indexed;
import org.hibernate.search.annotations.IndexedEmbedded;
import org.hibernate.search.bridge.builtin.IntegerBridge;
import  org.apache.commons.lang.builder.HashCodeBuilder;
import  org.apache.commons.lang.builder.EqualsBuilder;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.CascadeType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.Lob;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

import javax.xml.bind.annotation.XmlRootElement;

import java.io.Serializable;
import java.math.BigDecimal;

@Entity
@Table(name="msg_message", uniqueConstraints = @UniqueConstraint(columnNames={"strAHName"}))
@Indexed
@XmlRootElement
public class Message extends DataEntity implements Serializable {
    /**
	 * 
	 */
	private static final long serialVersionUID = 1762097433358587493L;
	private String strAHName;
    private String strAHDesc;
    private String strAHDesc1;
    private String strContent1;
    private String strContent2;
    private String strContent3;
    private String strContent4;
    private String strContent5;
    private short nStatus;
    private short nLevel;
    private Short nEndType;
    private Short nDelay;
    private short nAutoUpdate;
    private short uiOutput;
    private short nLayout;
    private Short nMessageZone;
    private short nOverlay;
    private boolean bStartImm;
    private boolean bEndManual;
    private Date dtStartTime;
    private Date dtEndTime;
    private Date dtStopTime;
    private Date dtCreateTime;
     
    @JsonProperty(value = "strAHName")
    @Column(name="strAHName", nullable=false, length=20)
    @Field
    public String getAHName(){
        return this.strAHName;
    }
    
    public void setAHName(String strAHName){
        this.strAHName = strAHName;
    }
    
    @JsonProperty(value = "strAHDesc")
    @Column(name="strAHDesc", length=100)
    @Field
    public String getAHDesc(){
        return this.strAHDesc;
    }
    
    public void setAHDesc(String strAHDesc){
        this.strAHDesc = strAHDesc;
    }
    
    @JsonProperty(value = "strAHDesc1")
    @Column(name="strAHDesc1", length=100)
    @Field
    public String getAHDesc1(){
        return this.strAHDesc1;
    }
    
    public void setAHDesc1(String strAHDesc1){
        this.strAHDesc1 = strAHDesc1;
    }
    
    @JsonProperty(value = "strContent1")
    @Column(name="strContent1", length=140)
    @Field
    public String getContent1(){
        return this.strContent1;
    }
    
    public void setContent1(String strContent1){
        this.strContent1 = strContent1;
    }
    
    @JsonProperty(value = "strContent2")
    @Column(name="strContent2", length=140)
    @Field
    public String getContent2(){
        return this.strContent2;
    }
    
    public void setContent2(String strContent2){
        this.strContent2 = strContent2;
    }
    
    @JsonProperty(value = "strContent3")
    @Column(name="strContent3", length=140)
    @Field
    public String getContent3(){
        return this.strContent3;
    }
    
    public void setContent3(String strContent3){
        this.strContent3 = strContent3;
    }
    
    @JsonProperty(value = "strContent4")
    @Column(name="strContent4", length=140)
    @Field
    public String getContent4(){
        return this.strContent4;
    }
    
    public void setContent4(String strContent4){
        this.strContent4 = strContent4;
    }
    
    @JsonProperty(value = "strContent5")
    @Column(name="strContent5", length=140)
    @Field
    public String getContent5(){
        return this.strContent5;
    }
    
    public void setContent5(String strContent5){
        this.strContent5 = strContent5;
    }
    
    @JsonProperty(value = "nStatus")
    @Column(name="nStatus", nullable=false)
    @Field
    public short getStatus(){
        return this.nStatus;
    }
    
    public void setStatus(short nStatus){
        this.nStatus = nStatus;
    }
    
    @JsonProperty(value = "nLevel")
    @Column(name="nLevel", nullable=false)
    @Field
    public short getLevel(){
        return this.nLevel;
    }
    
    public void setLevel(short nLevel){
        this.nLevel = nLevel;
    }
    
    @JsonProperty(value = "nEndType")
    @Column(name="nEndType")
    @Field
    public Short getEndType(){
        return this.nEndType;
    }
    
    public void setEndType(Short nEndType){
        this.nEndType = nEndType;
    }
    
    @JsonProperty(value = "nDelay")
    @Column(name="nDelay")
    @Field
    public Short getDelay(){
        return this.nDelay;
    }
    
    public void setDelay(Short nDelay){
        this.nDelay = nDelay;
    }
    
    @JsonProperty(value = "nAutoUpdate")
    @Column(name="nAutoUpdate", nullable=false)
    @Field
    public short getAutoUpdate(){
        return this.nAutoUpdate;
    }
    
    public void setAutoUpdate(short nAutoUpdate){
        this.nAutoUpdate = nAutoUpdate;
    }
    
    @JsonProperty(value = "uiOutput")
    @Column(name="uiOutput", nullable=false)
    @Field
    public short getOutput(){
        return this.uiOutput;
    }
    
    public void setOutput(short uiOutput){
        this.uiOutput = uiOutput;
    }
    
    @JsonProperty(value = "nLayout")
    @Column(name="nLayout", nullable=false)
    @Field
    public short getLayout(){
        return this.nLayout;
    }
    
    public void setLayout(short nLayout){
        this.nLayout = nLayout;
    }
    
    @JsonProperty(value = "nMessageZone")
    @Column(name="nMessageZone")
    @Field
    public Short getMessageZone(){
        return this.nMessageZone;
    }
    
    public void setMessageZone(Short nMessageZone){
        this.nMessageZone = nMessageZone;
    }
    
    @JsonProperty(value = "nOverlay")
    @Column(name="nOverlay", nullable=false)
    @Field
    public short getOverlay(){
        return this.nOverlay;
    }
    
    public void setOverlay(short nOverlay){
        this.nOverlay = nOverlay;
    }
    
    @JsonProperty(value = "bStartImm")
    @Column(name="bStartImm", nullable=false)
    @Field
    public boolean isStartImm(){
        return this.bStartImm;
    }
    
    public void setStartImm(boolean bStartImm){
        this.bStartImm = bStartImm;
    }
    
    @JsonProperty(value = "bEndManual")
    @Column(name="bEndManual", nullable=false)
    @Field
    public boolean isEndManual(){
        return this.bEndManual;
    }
    
    public void setEndManual(boolean bEndManual){
        this.bEndManual = bEndManual;
    }
    
    @JsonProperty(value = "dtStartTime")
    @JsonSerialize(using = JsonDateSerializer.class)
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dtStartTime", nullable=false, length=19)
    @Field
    public Date getStartTime(){
        return this.dtStartTime;
    }
    
    public void setStartTime(Date dtStartTime){
        this.dtStartTime = dtStartTime;
    }
    
    @JsonProperty(value = "dtEndTime")
    @JsonSerialize(using = JsonDateSerializer.class)
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dtEndTime", nullable=false, length=19)
    @Field
    public Date getEndTime(){
        return this.dtEndTime;
    }
    
    public void setEndTime(Date dtEndTime){
        this.dtEndTime = dtEndTime;
    }
    
    @JsonProperty(value = "dtStopTime")
    @JsonSerialize(using = JsonDateSerializer.class)
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dtStopTime", length=19)
    @Field
    public Date getStopTime(){
        return this.dtStopTime;
    }
    
    public void setStopTime(Date dtStopTime){
        this.dtStopTime = dtStopTime;
    }
    
    @JsonProperty(value = "dtCreateTime")
    @JsonSerialize(using = JsonDateSerializer.class)
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dtCreateTime", nullable=false, length=19)
    @Field
    public Date getCreateTime(){
        return this.dtCreateTime;
    }
    
    public void setCreateTime(Date dtCreateTime){
        this.dtCreateTime = dtCreateTime;
    }
    
    /**
    * {@inheritDoc}
    */
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        Message pojo = (Message)o;
        return (new EqualsBuilder()
             .append(strAHName, pojo.strAHName)
             .append(strAHDesc, pojo.strAHDesc)
             .append(strAHDesc1, pojo.strAHDesc1)
             .append(strContent1, pojo.strContent1)
             .append(strContent2, pojo.strContent2)
             .append(strContent3, pojo.strContent3)
             .append(strContent4, pojo.strContent4)
             .append(strContent5, pojo.strContent5)
             .append(nStatus, pojo.nStatus)
             .append(nLevel, pojo.nLevel)
             .append(nEndType, pojo.nEndType)
             .append(nDelay, pojo.nDelay)
             .append(nAutoUpdate, pojo.nAutoUpdate)
             .append(uiOutput, pojo.uiOutput)
             .append(nLayout, pojo.nLayout)
             .append(nMessageZone, pojo.nMessageZone)
             .append(nOverlay, pojo.nOverlay)
             .append(bStartImm, pojo.bStartImm)
             .append(bEndManual, pojo.bEndManual)
             .append(dtStartTime, pojo.dtStartTime)
             .append(dtEndTime, pojo.dtEndTime)
             .append(dtStopTime, pojo.dtStopTime)
             .append(dtCreateTime, pojo.dtCreateTime)
             ).isEquals();
    }


    /**
    * {@inheritDoc}
    */
     public int hashCode() {
        return   new  HashCodeBuilder( 17 ,  37 )
             .append(strAHName)
             .append(strAHDesc)
             .append(strAHDesc1)
             .append(strContent1)
             .append(strContent2)
             .append(strContent3)
             .append(strContent4)
             .append(strContent5)
             .append(nStatus)
             .append(nLevel)
             .append(nEndType)
             .append(nDelay)
             .append(nAutoUpdate)
             .append(uiOutput)
             .append(nLayout)
             .append(nMessageZone)
             .append(nOverlay)
             .append(bStartImm)
             .append(bEndManual)
             .append(dtStartTime)
             .append(dtEndTime)
             .append(dtStopTime)
             .append(dtCreateTime)
             .toHashCode();
    }


    /**
    * {@inheritDoc}
    */
     public String toString() {
        StringBuffer sb = new StringBuffer(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Id").append("='").append(getId()).append("', ");
        sb.append("strAHName").append("='").append(getAHName()).append("', ");
        sb.append("strAHDesc").append("='").append(getAHDesc()).append("', ");
        sb.append("strAHDesc1").append("='").append(getAHDesc1()).append("', ");
        sb.append("strContent1").append("='").append(getContent1()).append("', ");
        sb.append("strContent2").append("='").append(getContent2()).append("', ");
        sb.append("strContent3").append("='").append(getContent3()).append("', ");
        sb.append("strContent4").append("='").append(getContent4()).append("', ");
        sb.append("strContent5").append("='").append(getContent5()).append("', ");
        sb.append("nStatus").append("='").append(getStatus()).append("', ");
        sb.append("nLevel").append("='").append(getLevel()).append("', ");
        sb.append("nEndType").append("='").append(getEndType()).append("', ");
        sb.append("nDelay").append("='").append(getDelay()).append("', ");
        sb.append("nAutoUpdate").append("='").append(getAutoUpdate()).append("', ");
        sb.append("uiOutput").append("='").append(getOutput()).append("', ");
        sb.append("nLayout").append("='").append(getLayout()).append("', ");
        sb.append("nMessageZone").append("='").append(getMessageZone()).append("', ");
        sb.append("nOverlay").append("='").append(getOverlay()).append("', ");
        sb.append("bStartImm").append("='").append(isStartImm()).append("', ");
        sb.append("bEndManual").append("='").append(isEndManual()).append("', ");
        sb.append("dtStartTime").append("='").append(getStartTime()).append("', ");
        sb.append("dtEndTime").append("='").append(getEndTime()).append("', ");
        sb.append("dtStopTime").append("='").append(getStopTime()).append("', ");
        sb.append("dtCreateTime").append("='").append(getCreateTime()).append("', ");
        sb.append("]");
        
        return sb.toString();
    }

}