/**
 * The contents of this file are subject to the license and copyright
 * detailed in the LICENSE and NOTICE files at the root of the source
 * tree and available online at
 *
 * https://github.com/chinamds/license/
 */
// Created using LayerGen 4.0

package com.mds.aiotplayer.msg.model;

import com.mds.aiotplayer.common.model.DataEntity;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.mds.aiotplayer.common.model.JsonDateSerializer;

import org.hibernate.annotations.Type;
import org.hibernate.search.annotations.DocumentId;
import org.hibernate.search.annotations.Field;
import org.hibernate.search.annotations.FieldBridge;
import org.hibernate.search.annotations.Indexed;
import org.hibernate.search.annotations.IndexedEmbedded;
import org.hibernate.search.bridge.builtin.IntegerBridge;
import  org.apache.commons.lang.builder.HashCodeBuilder;
import  org.apache.commons.lang.builder.EqualsBuilder;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.CascadeType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.Lob;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

import javax.xml.bind.annotation.XmlRootElement;

import java.io.Serializable;
import java.math.BigDecimal;

@Entity
@Table(name="msg_messagezone")
@Indexed
@XmlRootElement
public class MessageZone extends DataEntity implements Serializable {
    /**
	 * 
	 */
	private static final long serialVersionUID = -7709357779472534388L;
    private AHMessage aHMessage;
    private Short nZoneIndex;
    private Short nZoneType;
    private String strZoneFile;
    private String strZoneOffineFile;
    private Integer crZoneBGColor;
    private String strZoneBGFile;
    private boolean bZoneSelectBgPic;
    private boolean bChkZone;
    private boolean bDDERefresh;
    private Short nZoom;
    private Float dAspect;
    private Float dVolume;
    private Float dSpeed;
    private boolean bZoneMute;
    private boolean bZoneRatio;
    private Float dZoneDuration;
    private Short nZonePort;
    private Short nZoneEffectType;
    private Short nZoneOrientation;
    private Short nZoneMotion;
    private Short nZoneDelay;
    private Short nZoneDirection;
    private boolean bZoneChkMpeg2;
    private Short nZoneTVSource;
    private Short nZoneTVStandard;
    private Short nZoneTVInput;
    private Short nZoneTVInputType;
    private Short nZoneTVTuningSpace;
    private Short nZoneTVCountry;
    private Integer lFrequency;
    private String strZoneTVChannel;
    private String strZoneTVSource;
    private Short nAudioSource;
    private Short nAudioStandard;
    private String strAudioSource;
    private String strAudioDevice;
    private Long uiChannelID;
    private String strWebCharset;
    private Short nWebZoom;
    private byte bAlpha;
         
    /**
	 * @return the aHMessage
	 */
    @ManyToOne
    @JoinColumn(name="ahmessage_id", nullable=false)
	public AHMessage getAHMessage() {
		return aHMessage;
	}

	/**
	 * @param aHMessage the aHMessage to set
	 */
	public void setAHMessage(AHMessage aHMessage) {
		this.aHMessage = aHMessage;
	}

	@JsonProperty(value = "nZoneIndex")
    @Column(name="nZoneIndex")
    @Field
    public Short getZoneIndex(){
        return this.nZoneIndex;
    }
    
    public void setZoneIndex(Short nZoneIndex){
        this.nZoneIndex = nZoneIndex;
    }
    
    @JsonProperty(value = "nZoneType")
    @Column(name="nZoneType")
    @Field
    public Short getZoneType(){
        return this.nZoneType;
    }
    
    public void setZoneType(Short nZoneType){
        this.nZoneType = nZoneType;
    }
    
    @JsonProperty(value = "strZoneFile")
    @Column(name="strZoneFile", nullable=false, length=1024)
    @Field
    public String getZoneFile(){
        return this.strZoneFile;
    }
    
    public void setZoneFile(String strZoneFile){
        this.strZoneFile = strZoneFile;
    }
    
    @JsonProperty(value = "strZoneOffineFile")
    @Column(name="strZoneOffineFile", length=1024)
    @Field
    public String getZoneOffineFile(){
        return this.strZoneOffineFile;
    }
    
    public void setZoneOffineFile(String strZoneOffineFile){
        this.strZoneOffineFile = strZoneOffineFile;
    }
    
    @JsonProperty(value = "crZoneBGColor")
    @Column(name="crZoneBGColor")
    @Field
    public Integer getZoneBGColor(){
        return this.crZoneBGColor;
    }
    
    public void setZoneBGColor(Integer crZoneBGColor){
        this.crZoneBGColor = crZoneBGColor;
    }
    
    @JsonProperty(value = "strZoneBGFile")
    @Column(name="strZoneBGFile", length=1024)
    @Field
    public String getZoneBGFile(){
        return this.strZoneBGFile;
    }
    
    public void setZoneBGFile(String strZoneBGFile){
        this.strZoneBGFile = strZoneBGFile;
    }
    
    @JsonProperty(value = "bZoneSelectBgPic")
    @Column(name="bZoneSelectBgPic", nullable=false)
    @Field
    public boolean isZoneSelectBgPic(){
        return this.bZoneSelectBgPic;
    }
    
    public void setZoneSelectBgPic(boolean bZoneSelectBgPic){
        this.bZoneSelectBgPic = bZoneSelectBgPic;
    }
    
    @JsonProperty(value = "bChkZone")
    @Column(name="bChkZone", nullable=false)
    @Field
    public boolean isChkZone(){
        return this.bChkZone;
    }
    
    public void setChkZone(boolean bChkZone){
        this.bChkZone = bChkZone;
    }
    
    @JsonProperty(value = "bDDERefresh")
    @Column(name="bDDERefresh", nullable=false)
    @Field
    public boolean isDDERefresh(){
        return this.bDDERefresh;
    }
    
    public void setDDERefresh(boolean bDDERefresh){
        this.bDDERefresh = bDDERefresh;
    }
    
    @JsonProperty(value = "nZoom")
    @Column(name="nZoom")
    @Field
    public Short getZoom(){
        return this.nZoom;
    }
    
    public void setZoom(Short nZoom){
        this.nZoom = nZoom;
    }
    
    @JsonProperty(value = "dAspect")
    @Column(name="dAspect")
    @Field
    public Float getAspect(){
        return this.dAspect;
    }
    
    public void setAspect(Float dAspect){
        this.dAspect = dAspect;
    }
    
    @JsonProperty(value = "dVolume")
    @Column(name="dVolume")
    @Field
    public Float getVolume(){
        return this.dVolume;
    }
    
    public void setVolume(Float dVolume){
        this.dVolume = dVolume;
    }
    
    @JsonProperty(value = "dSpeed")
    @Column(name="dSpeed")
    @Field
    public Float getSpeed(){
        return this.dSpeed;
    }
    
    public void setSpeed(Float dSpeed){
        this.dSpeed = dSpeed;
    }
    
    @JsonProperty(value = "bZoneMute")
    @Column(name="bZoneMute")
    @Field
    public boolean isZoneMute(){
        return this.bZoneMute;
    }
    
    public void setZoneMute(boolean bZoneMute){
        this.bZoneMute = bZoneMute;
    }
    
    @JsonProperty(value = "bZoneRatio")
    @Column(name="bZoneRatio")
    @Field
    public boolean isZoneRatio(){
        return this.bZoneRatio;
    }
    
    public void setZoneRatio(boolean bZoneRatio){
        this.bZoneRatio = bZoneRatio;
    }
    
    @JsonProperty(value = "dZoneDuration")
    @Column(name="dZoneDuration")
    @Field
    public Float getZoneDuration(){
        return this.dZoneDuration;
    }
    
    public void setZoneDuration(Float dZoneDuration){
        this.dZoneDuration = dZoneDuration;
    }
    
    @JsonProperty(value = "nZonePort")
    @Column(name="nZonePort")
    @Field
    public Short getZonePort(){
        return this.nZonePort;
    }
    
    public void setZonePort(Short nZonePort){
        this.nZonePort = nZonePort;
    }
    
    @JsonProperty(value = "nZoneEffectType")
    @Column(name="nZoneEffectType")
    @Field
    public Short getZoneEffectType(){
        return this.nZoneEffectType;
    }
    
    public void setZoneEffectType(Short nZoneEffectType){
        this.nZoneEffectType = nZoneEffectType;
    }
    
    @JsonProperty(value = "nZoneOrientation")
    @Column(name="nZoneOrientation")
    @Field
    public Short getZoneOrientation(){
        return this.nZoneOrientation;
    }
    
    public void setZoneOrientation(Short nZoneOrientation){
        this.nZoneOrientation = nZoneOrientation;
    }
    
    @JsonProperty(value = "nZoneMotion")
    @Column(name="nZoneMotion")
    @Field
    public Short getZoneMotion(){
        return this.nZoneMotion;
    }
    
    public void setZoneMotion(Short nZoneMotion){
        this.nZoneMotion = nZoneMotion;
    }
    
    @JsonProperty(value = "nZoneDelay")
    @Column(name="nZoneDelay")
    @Field
    public Short getZoneDelay(){
        return this.nZoneDelay;
    }
    
    public void setZoneDelay(Short nZoneDelay){
        this.nZoneDelay = nZoneDelay;
    }
    
    @JsonProperty(value = "nZoneDirection")
    @Column(name="nZoneDirection")
    @Field
    public Short getZoneDirection(){
        return this.nZoneDirection;
    }
    
    public void setZoneDirection(Short nZoneDirection){
        this.nZoneDirection = nZoneDirection;
    }
    
    @JsonProperty(value = "bZoneChkMpeg2")
    @Column(name="bZoneChkMpeg2")
    @Field
    public boolean isZoneChkMpeg2(){
        return this.bZoneChkMpeg2;
    }
    
    public void setZoneChkMpeg2(boolean bZoneChkMpeg2){
        this.bZoneChkMpeg2 = bZoneChkMpeg2;
    }
    
    @JsonProperty(value = "nZoneTVSource")
    @Column(name="nZoneTVSource")
    @Field
    public Short getZoneTVSource(){
        return this.nZoneTVSource;
    }
    
    public void setZoneTVSource(Short nZoneTVSource){
        this.nZoneTVSource = nZoneTVSource;
    }
    
    @JsonProperty(value = "nZoneTVStandard")
    @Column(name="nZoneTVStandard")
    @Field
    public Short getZoneTVStandard(){
        return this.nZoneTVStandard;
    }
    
    public void setZoneTVStandard(Short nZoneTVStandard){
        this.nZoneTVStandard = nZoneTVStandard;
    }
    
    @JsonProperty(value = "nZoneTVInput")
    @Column(name="nZoneTVInput")
    @Field
    public Short getZoneTVInput(){
        return this.nZoneTVInput;
    }
    
    public void setZoneTVInput(Short nZoneTVInput){
        this.nZoneTVInput = nZoneTVInput;
    }
    
    @JsonProperty(value = "nZoneTVInputType")
    @Column(name="nZoneTVInputType")
    @Field
    public Short getZoneTVInputType(){
        return this.nZoneTVInputType;
    }
    
    public void setZoneTVInputType(Short nZoneTVInputType){
        this.nZoneTVInputType = nZoneTVInputType;
    }
    
    @JsonProperty(value = "nZoneTVTuningSpace")
    @Column(name="nZoneTVTuningSpace")
    @Field
    public Short getZoneTVTuningSpace(){
        return this.nZoneTVTuningSpace;
    }
    
    public void setZoneTVTuningSpace(Short nZoneTVTuningSpace){
        this.nZoneTVTuningSpace = nZoneTVTuningSpace;
    }
    
    @JsonProperty(value = "nZoneTVCountry")
    @Column(name="nZoneTVCountry")
    @Field
    public Short getZoneTVCountry(){
        return this.nZoneTVCountry;
    }
    
    public void setZoneTVCountry(Short nZoneTVCountry){
        this.nZoneTVCountry = nZoneTVCountry;
    }
    
    @JsonProperty(value = "lFrequency")
    @Column(name="lFrequency")
    @Field
    public Integer getFrequency(){
        return this.lFrequency;
    }
    
    public void setFrequency(Integer lFrequency){
        this.lFrequency = lFrequency;
    }
    
    @JsonProperty(value = "strZoneTVChannel")
    @Column(name="strZoneTVChannel", length=20)
    @Field
    public String getZoneTVChannel(){
        return this.strZoneTVChannel;
    }
    
    public void setZoneTVChannel(String strZoneTVChannel){
        this.strZoneTVChannel = strZoneTVChannel;
    }
    
    @JsonProperty(value = "strZoneTVSource")
    @Column(name="strZoneTVSource", length=100)
    @Field
    public String getZoneTVSourceString(){
        return this.strZoneTVSource;
    }
    
    public void setZoneTVSourceString(String strZoneTVSource){
        this.strZoneTVSource = strZoneTVSource;
    }
    
    @JsonProperty(value = "nAudioSource")
    @Column(name="nAudioSource")
    @Field
    public Short getAudioSource(){
        return this.nAudioSource;
    }
    
    public void setAudioSource(Short nAudioSource){
        this.nAudioSource = nAudioSource;
    }
    
    @JsonProperty(value = "nAudioStandard")
    @Column(name="nAudioStandard")
    @Field
    public Short getAudioStandard(){
        return this.nAudioStandard;
    }
    
    public void setAudioStandard(Short nAudioStandard){
        this.nAudioStandard = nAudioStandard;
    }
    
    @JsonProperty(value = "strAudioSource")
    @Column(name="strAudioSource", length=100)
    @Field
    public String getAudioSourceString(){
        return this.strAudioSource;
    }
    
    public void setAudioSourceString(String strAudioSource){
        this.strAudioSource = strAudioSource;
    }
    
    @JsonProperty(value = "strAudioDevice")
    @Column(name="strAudioDevice", length=100)
    @Field
    public String getAudioDevice(){
        return this.strAudioDevice;
    }
    
    public void setAudioDevice(String strAudioDevice){
        this.strAudioDevice = strAudioDevice;
    }
    
    @JsonProperty(value = "uiChannelID")
    @Column(name="uiChannelID")
    @Field
    public Long getChannelId(){
        return this.uiChannelID;
    }
    
    public void setChannelId(Long uiChannelID){
        this.uiChannelID = uiChannelID;
    }
    
    @JsonProperty(value = "strWebCharset")
    @Column(name="strWebCharset", length=20)
    @Field
    public String getWebCharset(){
        return this.strWebCharset;
    }
    
    public void setWebCharset(String strWebCharset){
        this.strWebCharset = strWebCharset;
    }
    
    @JsonProperty(value = "nWebZoom")
    @Column(name="nWebZoom")
    @Field
    public Short getWebZoom(){
        return this.nWebZoom;
    }
    
    public void setWebZoom(Short nWebZoom){
        this.nWebZoom = nWebZoom;
    }
    
    @JsonProperty(value = "bAlpha")
    @Column(name="bAlpha", nullable=false)
    @Type(type="org.hibernate.type.ByteType")
    @FieldBridge(impl = IntegerBridge.class)
    @Field
    public byte getBAlpha(){
        return this.bAlpha;
    }
    
    public void setBAlpha(byte bAlpha){
        this.bAlpha = bAlpha;
    }
    


    /**
    * {@inheritDoc}
    */
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        MessageZone pojo = (MessageZone)o;
        return (new EqualsBuilder()
             .append(getAHMessage().getId(), pojo.getAHMessage().getId())
             .append(nZoneIndex, pojo.nZoneIndex)
             .append(nZoneType, pojo.nZoneType)
             .append(strZoneFile, pojo.strZoneFile)
             .append(strZoneOffineFile, pojo.strZoneOffineFile)
             .append(crZoneBGColor, pojo.crZoneBGColor)
             .append(strZoneBGFile, pojo.strZoneBGFile)
             .append(bZoneSelectBgPic, pojo.bZoneSelectBgPic)
             .append(bChkZone, pojo.bChkZone)
             .append(bDDERefresh, pojo.bDDERefresh)
             .append(nZoom, pojo.nZoom)
             .append(dAspect, pojo.dAspect)
             .append(dVolume, pojo.dVolume)
             .append(dSpeed, pojo.dSpeed)
             .append(bZoneMute, pojo.bZoneMute)
             .append(bZoneRatio, pojo.bZoneRatio)
             .append(dZoneDuration, pojo.dZoneDuration)
             .append(nZonePort, pojo.nZonePort)
             .append(nZoneEffectType, pojo.nZoneEffectType)
             .append(nZoneOrientation, pojo.nZoneOrientation)
             .append(nZoneMotion, pojo.nZoneMotion)
             .append(nZoneDelay, pojo.nZoneDelay)
             .append(nZoneDirection, pojo.nZoneDirection)
             .append(bZoneChkMpeg2, pojo.bZoneChkMpeg2)
             .append(nZoneTVSource, pojo.nZoneTVSource)
             .append(nZoneTVStandard, pojo.nZoneTVStandard)
             .append(nZoneTVInput, pojo.nZoneTVInput)
             .append(nZoneTVInputType, pojo.nZoneTVInputType)
             .append(nZoneTVTuningSpace, pojo.nZoneTVTuningSpace)
             .append(nZoneTVCountry, pojo.nZoneTVCountry)
             .append(lFrequency, pojo.lFrequency)
             .append(strZoneTVChannel, pojo.strZoneTVChannel)
             .append(strZoneTVSource, pojo.strZoneTVSource)
             .append(nAudioSource, pojo.nAudioSource)
             .append(nAudioStandard, pojo.nAudioStandard)
             .append(strAudioSource, pojo.strAudioSource)
             .append(strAudioDevice, pojo.strAudioDevice)
             .append(uiChannelID, pojo.uiChannelID)
             .append(strWebCharset, pojo.strWebCharset)
             .append(nWebZoom, pojo.nWebZoom)
             .append(bAlpha, pojo.bAlpha)
             ).isEquals();
    }


    /**
    * {@inheritDoc}
    */
     public int hashCode() {
        return   new  HashCodeBuilder( 17 ,  37 )
             .append(aHMessage.getId())
             .append(nZoneIndex)
             .append(nZoneType)
             .append(strZoneFile)
             .append(strZoneOffineFile)
             .append(crZoneBGColor)
             .append(strZoneBGFile)
             .append(bZoneSelectBgPic)
             .append(bChkZone)
             .append(bDDERefresh)
             .append(nZoom)
             .append(dAspect)
             .append(dVolume)
             .append(dSpeed)
             .append(bZoneMute)
             .append(bZoneRatio)
             .append(dZoneDuration)
             .append(nZonePort)
             .append(nZoneEffectType)
             .append(nZoneOrientation)
             .append(nZoneMotion)
             .append(nZoneDelay)
             .append(nZoneDirection)
             .append(bZoneChkMpeg2)
             .append(nZoneTVSource)
             .append(nZoneTVStandard)
             .append(nZoneTVInput)
             .append(nZoneTVInputType)
             .append(nZoneTVTuningSpace)
             .append(nZoneTVCountry)
             .append(lFrequency)
             .append(strZoneTVChannel)
             .append(strZoneTVSource)
             .append(nAudioSource)
             .append(nAudioStandard)
             .append(strAudioSource)
             .append(strAudioDevice)
             .append(uiChannelID)
             .append(strWebCharset)
             .append(nWebZoom)
             .append(bAlpha)
             .toHashCode();
    }


    /**
    * {@inheritDoc}
    */
     public String toString() {
        StringBuffer sb = new StringBuffer(getClass().getSimpleName());
        sb.append(" [");
        sb.append("uiID").append("='").append(getId()).append("', ");
        sb.append("ahmessage_id").append("='").append(getAHMessage().getId()).append("', ");
        sb.append("nZoneIndex").append("='").append(getZoneIndex()).append("', ");
        sb.append("nZoneType").append("='").append(getZoneType()).append("', ");
        sb.append("strZoneFile").append("='").append(getZoneFile()).append("', ");
        sb.append("strZoneOffineFile").append("='").append(getZoneOffineFile()).append("', ");
        sb.append("crZoneBGColor").append("='").append(getZoneBGColor()).append("', ");
        sb.append("strZoneBGFile").append("='").append(getZoneBGFile()).append("', ");
        sb.append("bZoneSelectBgPic").append("='").append(isZoneSelectBgPic()).append("', ");
        sb.append("bChkZone").append("='").append(isChkZone()).append("', ");
        sb.append("bDDERefresh").append("='").append(isDDERefresh()).append("', ");
        sb.append("nZoom").append("='").append(getZoom()).append("', ");
        sb.append("dAspect").append("='").append(getAspect()).append("', ");
        sb.append("dVolume").append("='").append(getVolume()).append("', ");
        sb.append("dSpeed").append("='").append(getSpeed()).append("', ");
        sb.append("bZoneMute").append("='").append(isZoneMute()).append("', ");
        sb.append("bZoneRatio").append("='").append(isZoneRatio()).append("', ");
        sb.append("dZoneDuration").append("='").append(getZoneDuration()).append("', ");
        sb.append("nZonePort").append("='").append(getZonePort()).append("', ");
        sb.append("nZoneEffectType").append("='").append(getZoneEffectType()).append("', ");
        sb.append("nZoneOrientation").append("='").append(getZoneOrientation()).append("', ");
        sb.append("nZoneMotion").append("='").append(getZoneMotion()).append("', ");
        sb.append("nZoneDelay").append("='").append(getZoneDelay()).append("', ");
        sb.append("nZoneDirection").append("='").append(getZoneDirection()).append("', ");
        sb.append("bZoneChkMpeg2").append("='").append(isZoneChkMpeg2()).append("', ");
        sb.append("nZoneTVSource").append("='").append(getZoneTVSource()).append("', ");
        sb.append("nZoneTVStandard").append("='").append(getZoneTVStandard()).append("', ");
        sb.append("nZoneTVInput").append("='").append(getZoneTVInput()).append("', ");
        sb.append("nZoneTVInputType").append("='").append(getZoneTVInputType()).append("', ");
        sb.append("nZoneTVTuningSpace").append("='").append(getZoneTVTuningSpace()).append("', ");
        sb.append("nZoneTVCountry").append("='").append(getZoneTVCountry()).append("', ");
        sb.append("lFrequency").append("='").append(getFrequency()).append("', ");
        sb.append("strZoneTVChannel").append("='").append(getZoneTVChannel()).append("', ");
        sb.append("strZoneTVSource").append("='").append(getZoneTVSourceString()).append("', ");
        sb.append("nAudioSource").append("='").append(getAudioSource()).append("', ");
        sb.append("nAudioStandard").append("='").append(getAudioStandard()).append("', ");
        sb.append("strAudioSource").append("='").append(getAudioSourceString()).append("', ");
        sb.append("strAudioDevice").append("='").append(getAudioDevice()).append("', ");
        sb.append("uiChannelID").append("='").append(getChannelId()).append("', ");
        sb.append("strWebCharset").append("='").append(getWebCharset()).append("', ");
        sb.append("nWebZoom").append("='").append(getWebZoom()).append("', ");
        sb.append("bAlpha").append("='").append(getBAlpha()).append("', ");
        sb.append("]");
        
        return sb.toString();
    }

}