/**
 * Copyright (c) 2016-2017 
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 */
// Created using LayerGen 4.0

package com.mds.aiotplayer.pm.model;

import com.mds.aiotplayer.common.model.DataEntity;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.mds.aiotplayer.common.model.JsonDateSerializer;

import org.hibernate.annotations.Type;
import org.hibernate.search.annotations.DocumentId;
import org.hibernate.search.annotations.Field;
import org.hibernate.search.annotations.FieldBridge;
import org.hibernate.search.annotations.Indexed;
import org.hibernate.search.annotations.IndexedEmbedded;
import org.hibernate.search.bridge.builtin.IntegerBridge;
import  org.apache.commons.lang.builder.HashCodeBuilder;
import  org.apache.commons.lang.builder.EqualsBuilder;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.CascadeType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.Lob;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

import javax.xml.bind.annotation.XmlRootElement;

import java.io.Serializable;
import java.math.BigDecimal;

@Entity
@Table(name="pm_playeroutputs", uniqueConstraints = @UniqueConstraint(columnNames={"player_id", "uiOutput"}))
@Indexed
@XmlRootElement
public class PlayerOutput extends DataEntity implements Serializable {
    /**
	 * 
	 */
	private static final long serialVersionUID = -8714082085317655899L;
	private Player player;
    private short uiOutput;
    private String strName;
    private String strLocation;
 
        
    /**
	 * @return the player
	 */
    @ManyToOne
    @JoinColumn(name="player_id", nullable=false)
	public Player getPlayer() {
		return player;
	}

	/**
	 * @param player the player to set
	 */
	public void setPlayer(Player player) {
		this.player = player;
	}

	@JsonProperty(value = "uiOutput")
    @Column(name="uiOutput", nullable=false)
    @Field
    public short getOutput(){
        return this.uiOutput;
    }
    
    public void setOutput(short uiOutput){
        this.uiOutput = uiOutput;
    }
    
    @JsonProperty(value = "strName")
    @Column(name="strName", length=50)
    @Field
    public String getName(){
        return this.strName;
    }
    
    public void setName(String strName){
        this.strName = strName;
    }
    
    @JsonProperty(value = "strLocation")
    @Column(name="strLocation", length=255)
    @Field
    public String getLocation(){
        return this.strLocation;
    }
    
    public void setLocation(String strLocation){
        this.strLocation = strLocation;
    }
    


    /**
    * {@inheritDoc}
    */
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        PlayerOutput pojo = (PlayerOutput)o;
        return (new EqualsBuilder()
             .append(uiOutput, pojo.uiOutput)
             .append(strName, pojo.strName)
             .append(strLocation, pojo.strLocation)
             ).isEquals();
    }


    /**
    * {@inheritDoc}
    */
     public int hashCode() {
        return   new  HashCodeBuilder( 17 ,  37 )
             .append(uiOutput)
             .append(strName)
             .append(strLocation)
             .toHashCode();
    }


    /**
    * {@inheritDoc}
    */
     public String toString() {
        StringBuffer sb = new StringBuffer(getClass().getSimpleName());
        sb.append(" [");
        sb.append("id").append("='").append(getId()).append("', ");
        sb.append("uiOutput").append("='").append(getOutput()).append("', ");
        sb.append("strName").append("='").append(getName()).append("', ");
        sb.append("strLocation").append("='").append(getLocation()).append("', ");
        sb.append("]");
        
        return sb.toString();
    }

}