/**
 * The contents of this file are subject to the license and copyright
 * detailed in the LICENSE and NOTICE files at the root of the source
 * tree and available online at
 *
 * https://github.com/chinamds/license/
 */
// Created using LayerGen 4.0

package com.mds.aiotplayer.common.model;

import com.mds.aiotplayer.common.model.IdEntity;

import com.fasterxml.jackson.annotation.JsonProperty;

import org.hibernate.annotations.Type;
import org.hibernate.search.annotations.Field;
import org.hibernate.search.annotations.FieldBridge;
import org.hibernate.search.bridge.builtin.IntegerBridge;
import  org.apache.commons.lang.builder.HashCodeBuilder;
import  org.apache.commons.lang.builder.EqualsBuilder;

import javax.persistence.Column;
import javax.persistence.MappedSuperclass;


import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;

import java.io.Serializable;

@SuppressWarnings("serial")
@MappedSuperclass
@XmlAccessorType(XmlAccessType.NONE)
public class BaseZone extends IdEntity implements Serializable {
    /**
	 * 
	 */
    protected short zoneIndex;
    protected Short zoneType;
    protected String zoneFile;
    protected String zoneOffineFile;
    protected Integer zoneBGColor;
    protected String zoneBGFile;
    protected boolean zoneSelectBgPic;
    protected boolean chkZone; 
    protected boolean ddeRefresh;
    protected Short zoom;
    protected Float aspect;
    protected Float volume;
    protected Float speed;
    protected boolean zoneMute;
    protected boolean zoneRatio;
    protected Float zoneDuration;
    protected Integer zonePort;
    protected Short zoneEffectType;
    protected Short zoneOrientation;
    protected Short zoneMotion;
    protected Short zoneDelay;
    protected Short zoneDirection;
    protected boolean zoneChkMpeg2;
    protected Short zoneTVSource;
    protected Short zoneTVStandard;
    protected Short zoneTVInput;
    protected Short zoneTVInputType;
    protected Short zoneTVTuningSpace;
    protected Short zoneTVCountry;
    protected Integer frequency;
    protected String zoneTVChannel;
    protected String zoneTVSourceName;
    protected Short audioSource;
    protected Short audioStandard;
    protected String audioSourceName;
    protected String audioDevice;
    protected Long channelId;
    protected String webCharset;
    protected Short webZoom;
    protected Byte alpha;
    
    public BaseZone() {
    	super();
    	       	
		this.zoom = 0;
		this.aspect = 0.0f;
		this.volume = 0.0f;
		this.speed =  0.0f;
		this.alpha = 0;
	
		this.channelId = -1L;
		this.chkZone = false;
		this.zoneIndex = 0;
		this.zoneType = 0;
		this.zoneFile = "";
		this.zoneOffineFile = "";
		this.zoneBGColor = 0;
		this.zoneBGFile = "";
		this.zoneSelectBgPic = false;
	
		this.zoneMute = false;
		this.zoneRatio = false;
		this.zoneDuration = 10.0f;
		this.zonePort = 8080;
	
		this.zoneEffectType = 0;
		this.zoneOrientation = 0;
		this.zoneMotion = 0;
		this.zoneDelay = 0;
		this.zoneDirection = 0;
	
		this.zoneTVCountry = 86;
		this.zoneTVInput = -1;
		this.zoneTVInputType = 0;
		this.zoneTVTuningSpace = 86;
		this.zoneTVSource = -1;
		this.zoneTVStandard = -1;
		this.frequency = 0;
		this.zoneTVChannel = "";
	
		this.audioStandard = 0;
		this.audioSource = 0;
	
		this.zoneChkMpeg2 = false;
		this.ddeRefresh = false;
		this.zoneTVSourceName = "";
	
		this.webCharset = "";
		this.webZoom = 2;
    }
     
	@JsonProperty(value = "zoneIndex")
    @Column(name="zone_index", nullable=false)
    @Field
    public short getZoneIndex(){
        return this.zoneIndex;
    }
    
    public void setZoneIndex(short zoneIndex){
        this.zoneIndex = zoneIndex;
    }
    
    @JsonProperty(value = "zoneType")
    @Column(name="zone_type", nullable=true)
    @Field
    public Short getZoneType(){
        return this.zoneType;
    }
    
    public void setZoneType(Short zoneType){
        this.zoneType = zoneType;
    }
    
    @JsonProperty(value = "zoneFile")
    @Column(name="zone_file", nullable=true, length=1024)
    @Field
    public String getZoneFile(){
        return this.zoneFile;
    }
    
    public void setZoneFile(String zoneFile){
        this.zoneFile = zoneFile;
    }
    
    @JsonProperty(value = "zoneOffineFile")
    @Column(name="zone_offine_file", length=1024)
    @Field
    public String getZoneOffineFile(){
        return this.zoneOffineFile;
    }
    
    public void setZoneOffineFile(String zoneOffineFile){
        this.zoneOffineFile = zoneOffineFile;
    }
    
    @JsonProperty(value = "zoneBGColor")
    @Column(name="zone_bg_color", nullable=true)
    @Field
    public Integer getZoneBGColor(){
        return this.zoneBGColor;
    }
    
    public void setZoneBGColor(Integer zoneBGColor){
        this.zoneBGColor = zoneBGColor;
    }
    
    @JsonProperty(value = "zoneBGFile")
    @Column(name="zone_bg_file", length=1024)
    @Field
    public String getZoneBGFile(){
        return this.zoneBGFile;
    }
    
    public void setZoneBGFile(String zoneBGFile){
        this.zoneBGFile = zoneBGFile;
    }
    
    @JsonProperty(value = "zoneSelectBgPic")
    @Column(name="zone_select_bg_pic", nullable=true)
    @Field
    public boolean isZoneSelectBgPic(){
        return this.zoneSelectBgPic;
    }
    
    public void setZoneSelectBgPic(boolean zoneSelectBgPic){
        this.zoneSelectBgPic = zoneSelectBgPic;
    }
    
    @JsonProperty(value = "chkZone")
    @Column(name="chk_zone", nullable=true)
    @Field
    public boolean isChkZone(){
        return this.chkZone;
    }
    
    public void setChkZone(boolean chkZone){
        this.chkZone = chkZone;
    }
    
    @JsonProperty(value = "ddeRefresh")
    @Column(name="dde_refresh")
    @Field
    public boolean isDdeRefresh(){
        return this.ddeRefresh;
    }
    
    public void setDdeRefresh(boolean ddeRefresh){
        this.ddeRefresh = ddeRefresh;
    }
    
    @JsonProperty(value = "zoom")
    @Column(name="zoom")
    @Field
    public Short getZoom(){
        return this.zoom;
    }
    
    public void setZoom(Short zoom){
        this.zoom = zoom;
    }
    
    @JsonProperty(value = "aspect")
    @Column(name="aspect")
    @Field
    public Float getAspect(){
        return this.aspect;
    }
    
    public void setAspect(Float aspect){
        this.aspect = aspect;
    }
    
    @JsonProperty(value = "volume")
    @Column(name="volume")
    @Field
    public Float getVolume(){
        return this.volume;
    }
    
    public void setVolume(Float volume){
        this.volume = volume;
    }
    
    @JsonProperty(value = "speed")
    @Column(name="speed")
    @Field
    public Float getSpeed(){
        return this.speed;
    }
    
    public void setSpeed(Float speed){
        this.speed = speed;
    }
    
    @JsonProperty(value = "zoneMute")
    @Column(name="zone_mute")
    @Field
    public boolean isZoneMute(){
        return this.zoneMute;
    }
    
    public void setZoneMute(boolean zoneMute){
        this.zoneMute = zoneMute;
    }
    
    @JsonProperty(value = "zoneRatio")
    @Column(name="zone_ratio")
    @Field
    public boolean isZoneRatio(){
        return this.zoneRatio;
    }
    
    public void setZoneRatio(boolean zoneRatio){
        this.zoneRatio = zoneRatio;
    }
    
    @JsonProperty(value = "zoneDuration")
    @Column(name="zone_duration")
    @Field
    public Float getZoneDuration(){
        return this.zoneDuration;
    }
    
    public void setZoneDuration(Float zoneDuration){
        this.zoneDuration = zoneDuration;
    }
    
    @JsonProperty(value = "zonePort")
    @Column(name="zone_port")
    @Field
    public Integer getZonePort(){
        return this.zonePort;
    }
    
    public void setZonePort(Integer zonePort){
        this.zonePort = zonePort;
    }
    
    @JsonProperty(value = "zoneEffectType")
    @Column(name="zone_effect_type")
    @Field
    public Short getZoneEffectType(){
        return this.zoneEffectType;
    }
    
    public void setZoneEffectType(Short zoneEffectType){
        this.zoneEffectType = zoneEffectType;
    }
    
    @JsonProperty(value = "zoneOrientation")
    @Column(name="zone_orientation")
    @Field
    public Short getZoneOrientation(){
        return this.zoneOrientation;
    }
    
    public void setZoneOrientation(Short zoneOrientation){
        this.zoneOrientation = zoneOrientation;
    }
    
    @JsonProperty(value = "zoneMotion")
    @Column(name="zone_motion")
    @Field
    public Short getZoneMotion(){
        return this.zoneMotion;
    }
    
    public void setZoneMotion(Short zoneMotion){
        this.zoneMotion = zoneMotion;
    }
    
    @JsonProperty(value = "zoneDelay")
    @Column(name="zone_delay")
    @Field
    public Short getZoneDelay(){
        return this.zoneDelay;
    }
    
    public void setZoneDelay(Short zoneDelay){
        this.zoneDelay = zoneDelay;
    }
    
    @JsonProperty(value = "zoneDirection")
    @Column(name="zone_direction")
    @Field
    public Short getZoneDirection(){
        return this.zoneDirection;
    }
    
    public void setZoneDirection(Short zoneDirection){
        this.zoneDirection = zoneDirection;
    }
    
    @JsonProperty(value = "zoneChkMpeg2")
    @Column(name="zone_chk_mpeg2")
    @Field
    public boolean isZoneChkMpeg2(){
        return this.zoneChkMpeg2;
    }
    
    public void setZoneChkMpeg2(boolean zoneChkMpeg2){
        this.zoneChkMpeg2 = zoneChkMpeg2;
    }
    
    @JsonProperty(value = "zoneTVSource")
    @Column(name="zone_tv_Source")
    @Field
    public Short getZoneTVSource(){
        return this.zoneTVSource;
    }
    
    public void setZoneTVSource(Short zoneTVSource){
        this.zoneTVSource = zoneTVSource;
    }
    
    @JsonProperty(value = "zoneTVStandard")
    @Column(name="zone_tv_standard")
    @Field
    public Short getZoneTVStandard(){
        return this.zoneTVStandard;
    }
    
    public void setZoneTVStandard(Short zoneTVStandard){
        this.zoneTVStandard = zoneTVStandard;
    }
    
    @JsonProperty(value = "zoneTVInput")
    @Column(name="zone_tv_input")
    @Field
    public Short getZoneTVInput(){
        return this.zoneTVInput;
    }
    
    public void setZoneTVInput(Short zoneTVInput){
        this.zoneTVInput = zoneTVInput;
    }
    
    @JsonProperty(value = "zoneTVInputType")
    @Column(name="zone_tv_input_type")
    @Field
    public Short getZoneTVInputType(){
        return this.zoneTVInputType;
    }
    
    public void setZoneTVInputType(Short zoneTVInputType){
        this.zoneTVInputType = zoneTVInputType;
    }
    
    @JsonProperty(value = "zoneTVTuningSpace")
    @Column(name="zone_tv_tuning_space")
    @Field
    public Short getZoneTVTuningSpace(){
        return this.zoneTVTuningSpace;
    }
    
    public void setZoneTVTuningSpace(Short zoneTVTuningSpace){
        this.zoneTVTuningSpace = zoneTVTuningSpace;
    }
    
    @JsonProperty(value = "zoneTVCountry")
    @Column(name="zone_tv_country")
    @Field
    public Short getZoneTVCountry(){
        return this.zoneTVCountry;
    }
    
    public void setZoneTVCountry(Short zoneTVCountry){
        this.zoneTVCountry = zoneTVCountry;
    }
    
    @JsonProperty(value = "frequency")
    @Column(name="frequency")
    @Field
    public Integer getFrequency(){
        return this.frequency;
    }
    
    public void setFrequency(Integer frequency){
        this.frequency = frequency;
    }
    
    @JsonProperty(value = "zoneTVChannel")
    @Column(name="zone_tv_channel", length=20)
    @Field
    public String getZoneTVChannel(){
        return this.zoneTVChannel;
    }
    
    public void setZoneTVChannel(String zoneTVChannel){
        this.zoneTVChannel = zoneTVChannel;
    }
    
    @JsonProperty(value = "zoneTVSourceName")
    @Column(name="zone_tv_source_name", length=100)
    @Field
    public String getZoneTVSourceName(){
        return this.zoneTVSourceName;
    }
    
    public void setZoneTVSourceName(String zoneTVSourceName){
        this.zoneTVSourceName = zoneTVSourceName;
    }
    
    @JsonProperty(value = "audioSource")
    @Column(name="audio_source")
    @Field
    public Short getAudioSource(){
        return this.audioSource;
    }
    
    public void setAudioSource(Short audioSource){
        this.audioSource = audioSource;
    }
    
    @JsonProperty(value = "audioStandard")
    @Column(name="audio_standard")
    @Field
    public Short getAudioStandard(){
        return this.audioStandard;
    }
    
    public void setAudioStandard(Short audioStandard){
        this.audioStandard = audioStandard;
    }
    
    @JsonProperty(value = "audioSourceName")
    @Column(name="audio_source_name", length=100)
    @Field
    public String getAudioSourceName(){
        return this.audioSourceName;
    }
    
    public void setAudioSourceName(String audioSourceName){
        this.audioSourceName = audioSourceName;
    }
    
    @JsonProperty(value = "audioDevice")
    @Column(name="audio_device", length=100)
    @Field
    public String getAudioDevice(){
        return this.audioDevice;
    }
    
    public void setAudioDevice(String audioDevice){
        this.audioDevice = audioDevice;
    }
    
    @JsonProperty(value = "channelId")
    @Column(name="channel_id")
    @Field
    public Long getChannelId(){
        return this.channelId;
    }
    
    public void setChannelId(Long channelId){
        this.channelId = channelId;
    }
    
    @JsonProperty(value = "webCharset")
    @Column(name="web_charset", length=20)
    @Field
    public String getWebCharset(){
        return this.webCharset;
    }
    
    public void setWebCharset(String webCharset){
        this.webCharset = webCharset;
    }
    
    @JsonProperty(value = "webZoom")
    @Column(name="web_zoom")
    @Field
    public Short getWebZoom(){
        return this.webZoom;
    }
    
    public void setWebZoom(Short webZoom){
        this.webZoom = webZoom;
    }
    
    @JsonProperty(value = "alpha")
    @Column(name="alpha", nullable=true)
    @Type(type="org.hibernate.type.ByteType")
    @FieldBridge(impl = IntegerBridge.class)
    @Field
    public Byte getAlpha(){
        return this.alpha;
    }
    
    public void setAlpha(Byte alpha){
        this.alpha = alpha;
    }
    
}